myproject/OATS/urls.py
from django.urls import path
from OATS.views import *

app_name = 'OATS'
urlpatterns = [
    path('' , welcome),
    path('new-candidate' , candidateRegistrationForm , name='registrationForm'),
    path('store-candidate' , candidateRegistration , name='storeCandidate'),
    path('login' , loginView , name='login'),
    path('home' , candidateHome , name='home'),
    path('test-paper' , testPaper , name='testPaper'),
    path('calculate-result' , calculateTestResult , name='calculateTest'),
    path('test-history' , testResultHistory , name='testHistory'),
    path('result' , showTestResult , name='result'),
    path('logout' , logoutView , name='logout'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OATS/',include('OATS.urls')),
]

myproject/OATS/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    username = models.CharField(primary_key=True , max_length=20)
    password = models.CharField(null=False , max_length=20)
    name = models.CharField(null=False , max_length=30)
    test_attempted = models.IntegerField(default=0)
    points = models.FloatField(default=0.0)


class Question(models.Model):
    qid = models.BigAutoField(primary_key=True , auto_created=True)
    que = models.TextField()
    #options of the given question
    a = models.CharField(max_length=255)
    b = models.CharField(max_length=255)
    c = models.CharField(max_length=255)
    d = models.CharField(max_length=255)

    ans = models.CharField(max_length=2)

class Result(models.Model):
    resultid = models.BigAutoField(primary_key=True , auto_created=True)

    # we create foreign key this way
    username = models.ForeignKey(Candidate , on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    attempt = models.IntegerField()
    right = models.IntegerField()
    wrong = models.IntegerField()
    points = models.FloatField()
    

myproject/OATS/views.py
from django.shortcuts import render
from django.template import loader

# Create your views here.
from django.http import HttpResponse , HttpResponseRedirect
from OATS.models import *
import random 


def welcome(request):
    template = loader.get_template('welcome.html')
    return HttpResponse(template.render())

    
def candidateRegistrationForm(request):
    res = render(request , 'registration_form.html')
    return res


def candidateRegistration(request):
    if request.method == 'POST':
        username = request.POST['username']
        # check if user already exists
        if(len(Candidate.objects.filter(username = username))):
            userStatus = 1
        else:
            candidate = Candidate()
            candidate.username = username
            candidate.password = request.POST['password']
            candidate.name = request.POST['name']
            candidate.save()
            userStatus = 2
    else:
        userStatus = 3
    context = {'userStatus' : userStatus}

    res = render(request , 'registration.html' , context)
    return res




def loginView(request):
    if(request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        candidate = Candidate.objects.filter(username = username , password = password)
        if len(candidate) == 0 :
            loginError = "Invalid username or password"
            res = render(request , 'login.html',{'loginError' : loginError})
        else:
            # login success
            request.session['username'] = candidate[0].username
            request.session['name'] = candidate[0].name
            res = HttpResponseRedirect("home")
    else:
        res = render(request , 'login.html')
    return res


def candidateHome(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        res = render(request , 'home.html')
        return res
    

def testPaper(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect("login")   
    # fetch questions from database table
    n = int(request.GET['n'])
    question_pool = list(Question.objects.all())
    random.shuffle(question_pool)

    questions_list = question_pool[:n]
    context = {'questions' : questions_list}
    res = render(request , 'test_paper.html' , context)
    return res 
    


def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect("login")
    
    total_attempt = 0
    total_right = 0
    total_wrong = 0
    # points = 0

    qid_list = []
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question = Question.objects.get(qid = n)
        try:
            if question.ans == request.POST['q' + str(n)]:
                total_right += 1
            else:
                total_wrong += 1
            total_attempt += 1
        except:
            pass
    points = (total_right - total_wrong) / len(qid_list)*10
    # store result in result table 
    result = Result()
    result.username = Candidate.objects.get(username = request.session['username'])
    result.attempt = total_attempt
    result.right = total_right
    result.wrong = total_wrong
    result.points = points
    result.save()

    # update candidate table
    candidate = Candidate.objects.get(username = request.session['username'])
    candidate.test_attempted += 1
    candidate.points = (candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()

    return HttpResponseRedirect('result')


def testResultHistory(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect("login")
    candidate = Candidate.objects.filter(username = request.session['username'])
    results = Result.objects.filter(username_id = candidate[0].username)
    context = {'candidate' : candidate , 'results' : results}
    res = render(request , 'candidate_history.html' , context)
    return res


def showTestResult(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect("login")

    # fetch latest result from result table 
    result = Result.objects.filter(resultid = Result.objects.latest('resultid').resultid , username_id = request.session['username'])
    context = {'result' : result}
    res = render(request , 'show_result.html' , context)
    return res



def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect("login")

myproject/OATS/templates/candidate_history.html
{% extends 'main.html' %}

{% block title %}
    OATS - Candidate Result History
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:home' %}">DashBoard</a>
<a href="{% url 'OATS:logout' %}">Logout</a>
{% endblock %}



{% block content %}
<h1>Your Score Card</h1>
<p>Hi this table contains the number of times you have given the test and the score you have achieved on the scale of 10</p>

<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>

    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

myproject/OATS/templates/home.html
{% extends 'main.html' %}

{% block title %}
    OATS - Candidate Home Page
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:home' %}">DashBoard</a>
<a href="{% url 'OATS:logout' %}">Logout</a>
{% endblock %}

{% block content %}
<h1>Welcome {{request.session.name}} , to your home page</h1>

<div class="button-link">
    <a href="{% url 'OATS:testPaper' %}?n=1">Test Of 1 Question</a>
</div>


<div class="button-link">
    <a href="{% url 'OATS:testPaper' %}?n=2">Test Of 2 Questions</a>
</div>

<div class="button-link">
    <a href="{% url 'OATS:testPaper' %}?n=3">Test Of 3 Questions</a>
</div>


<div class="button-link">
    <a href="{% url 'OATS:testHistory' %}?n=3">Test History</a>
</div>
{% endblock %}

myproject/OATS/templates/login.html
{% extends 'main.html' %}

{% block title %}
OATS - Login Form
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:registrationForm' %}">SignUp</a>
{% endblock %}

{% block content %}
<div class="all-forms">
    {% if loginError %}
    <div class="error">{{loginError}}</div>
    {% endif %}
    <form action="{% url 'OATS:login' %}" method="POST">
        {% csrf_token %}

        <div class="form-unit">
            <label for="username">Username</label>
            <input type="text" name="username">
        </div>


        <div class="form-unit">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>


        <div class="form-unit">
            <input type="submit" value="Login">
            <input type="reset" value="Clear">
        </div>

    </form>
    New user <a href="{% url 'OATS:registrationForm' %}">Click Here to SignUp</a>
</div>
{% endblock %}

myproject/OATS/templates/main.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">

</head>

<body>
    <div class="top">
        <div class="sitename">
            <h1>Online Aptitude Testing System</h1>
        </div>
        <div class="menu">
            {% block top %}
            {% endblock %}
        </div>
    </div>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

myproject/OATS/templates/registration.html
{% extends 'main.html' %}

{% block title %}
OATS - Registration Status
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:registrationForm' %}">SignUp</a>
<a href="{% url 'OATS:login' %}">Login</a>
{% endblock %}


{% block content %}

{% if userStatus == 1 %}
<div class="userStatus">
    Sorry , username already exixts , try another one
    <a href="{% url 'OATS:registrationForm' %}">Back to Candidate Registration</a>
</div>

{% elif userStatus == 2 %}
<div class="userStatus">
    Congratulations ! user created successfully
    <a href="{% url 'OATS:login' %}">Login</a>
</div>

{% elif userStatus == 3 %}
<div class="userStatus">
    Oops ! Invalid data or improper request
    <a href="{% url 'OATS:registrationForm' %}">Back to Candidate Registration</a>

</div>
{% endif %}
{% endblock %}

myproject/OATS/templates/registration_form.html
{% extends 'main.html' %}

{% block title %}
    OATS - Registration Form
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:login' %}">Login</a>
{% endblock %}

{% block content %}
<div class="all-forms">
    <form action="{% url 'OATS:storeCandidate' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">

        <label for="password">Password</label>
        <input type="password" name="password">

        <label for="name">Name</label>
        <input type="text" name="name">

        <input type="submit" value="Submit">
        <input type="reset" value="Clear">
    </form>

    Already have an account , <a href="{% url 'OATS:login' %}">Click Here</a>
</div>
{% endblock %}

myproject/OATS/templates/show_result.html
{% extends 'main.html' %}

{% block title %}
OATS - Test Result
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:home' %}">DashBoard</a>
<a href="{% url 'OATS:logout' %}">Logout</a>
{% endblock %}

{% block content %}
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>

    {% for r in result %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

myproject/OATS/templates/test_paper.html
{% extends 'main.html' %}

{% block title %}
OATS - Test Paper
{% endblock title %}


{% block top %}
{% endblock %}

{% block content %}
<form action="{% url 'OATS:calculateTest' %}" method="POST">
    {% csrf_token %}
    {% for question in questions %}
    <div class="question">
        <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
        {{question.que}}
    </div>

    <div class="options"><input type="radio" name="q{{question.qid}}" value="a">{{question.a}}</div>

    <div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>

    <div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>

    <div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div>
{% endfor %}
<div><input type="submit" value="Submit"></div>
</form>
{% endblock %}

myproject/OATS/templates/welcome.html
{% extends 'main.html' %}

{% block title %}
Welcome to Online Aptitude Testing System
{% endblock title %}


{% block top %}
<a href="{% url 'OATS:registrationForm' %}">SignUp</a>
<a href="{% url 'OATS:login' %}">Login</a>
{% endblock %}

{% block content %}
<!-- <p>Welcome to Online Aptitude Testing System</p> -->
<p style="font-size: 20px;">Are you ready to challenge yourself and elevate your skills? Welcome
    to our cutting-edge platform designed to help you excel in aptitude
    testing! Whether you're preparing for competitive exams, job interviews,
    or simply want to sharpen your cognitive abilities, our platform provides the tools you need to succeed.</p>

<h3>What Makes Us Unique?</h3>
<h4 style="font-size: 22px;">Comprehensive Test Coverage: </h4>
<p style="font-size: 20px;">Our system offers a wide range of aptitude tests covering various disciplines, including
    mathematics,
    logical reasoning, verbal ability, and more. Each test is meticulously
    crafted to simulate real-world exam conditions, ensuring that you're fully prepared.
</p>

<h4 style="font-size: 22px;">Interactive User Experience:</h4>
<p style="font-size: 20px;">Experience seamless navigation and a user-friendly interface designed to enhance your
    learning journey.
    Dive into our tests effortlessly and track your progress with detailed performance analytics.</p>


<p style="font-size: 20px;">Get Started Today!Ready to embark on your journey towards mastery? Sign up now and take your first step towards acing your next aptitude test! Whether you're a student, 
    professional, or lifelong learner, our platform is your gateway to success.</p>

{% endblock %}